name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v2
      with:
        tags: beeradvisor:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: beeradvisor:latest
        options: -e TEMPLATE_PATH=/src/templates/ -p 80:4444
        run: /src/beeradvisor
        
    
